- name: Setup Nginx with Custom File
  hosts: servers
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Copy the custom HTML File
      copy:
        src: /home/ubuntu/website/
        dest: /var/www/html/

    - name: Restart Nginx
      service:
        name: nginx
        state: reloaded

    - name: Enable nginx
      systemd_service:
        name: nginx
        enabled: true
